package com.vaibh.controller;

// ...existing code...
// ...existing code...
// ...existing code...
// ...existing code...
// ...existing code...
// ...existing code...
import org.springframework.web.bind.annotation.RestController;

@RestController
public class VerificationController {
    // ...existing code...

    // ...existing code...

    // ...existing code...
    // ...existing code...




}
